### ISSUE TITLE
Elements with :only-child aren't displayed

### ISSUE THREAD

**Issue by leifbladt** [thoughtbot/capybara-webkit#524]
I'm working with the pseudo CSS class `:only-child`, to view a info text when a certain div contains no elements.

I can't test this behavior as these elements are not displayed with `capybara-webkit` (verified with a screenshot).

HTML snippet:

``` html
<div class="aa-parent">
  <div class="aa-empty-list">Info message on empty list</div>
</div>
```

CSS snippet:

``` css
.aa-parent .aa-empty-list { display: none; }
.aa-parent .aa-empty-list:only-child { display: block; }
```

Capybara configuration:

``` ruby
Capybara.configure do |config|
  config.match = :prefer_exact
  config.ignore_hidden_elements = true
end
```
