### ISSUE TITLE
Tests fail with OS X 10.9 and QT 5.2.0

### ISSUE THREAD

**Issue by betelgeuse** [thoughtbot/capybara-webkit#603]
I can't get tests to pass on OS X 10.9 and QT 5.2.0. Running fa8e377 with bundle update selenium-webdriver so it loads:

```
Failures:

  1) Capybara::Webkit::Connection forwards stderr to the given IO object
     Failure/Error: io.string.should =~ /hello world $/
       expected: /hello world $/
            got: "" (using =~)
       Diff:
       @@ -1,2 +1,2 @@
       -/hello world $/
       +""

     # ./spec/connection_spec.rb:32:in `block (2 levels) in <top (required)>'

  2) Capybara::Session webkit #fill_in on a pre-populated textfield with a reformatting onchange should trigger change when clearing field
     Failure/Error: @session.should have_selector(:css, '.change_event_triggered', :match => :one)
       expected #has_selector?(:css, ".change_event_triggered", {:match=>:one}) to return true, got false
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/expectations/handler.rb:36:in `handle_matcher'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/expectations/syntax.rb:53:in `should'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/spec/session/fill_in_spec.rb:138:in `block (3 levels) in <top (required)>'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:111:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:400:in `block in run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:381:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:80:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:17:in `block in autorun'

  3) Capybara::Session webkit #go_back should fetch a response from the driver from the previous page
     Failure/Error: @session.go_back
     NoMethodError:
       undefined method `go_back' for #<Capybara::Webkit::Driver:0x007fa4c21b2678>
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/session.rb:205:in `go_back'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/spec/session/go_back_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:111:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:400:in `block in run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:381:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:80:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:17:in `block in autorun'

  4) Capybara::Session webkit #go_forward should fetch a response from the driver from the previous page
     Failure/Error: @session.go_back
     NoMethodError:
       undefined method `go_back' for #<Capybara::Webkit::Driver:0x007fa4c21b2678>
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/session.rb:205:in `go_back'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/spec/session/go_forward_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:111:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:400:in `block in run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:381:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:80:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:17:in `block in autorun'

  5) Capybara::Session webkit node #set should allow me to change the contents of a contenteditable element
     Failure/Error: @session.find(:css,'#existing_content_editable').text.should == 'WYSIWYG'
       expected: "WYSIWYG"
            got: "Editable content" (using ==)
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:56:in `fail_with_message'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:94:in `__delegate_operator'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:84:in `eval_match'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:37:in `block in use_custom_matcher_or_delegate'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/spec/session/node_spec.rb:110:in `block (3 levels) in <top (required)>'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:111:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:400:in `block in run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:381:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:80:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:17:in `block in autorun'

  6) Capybara::Session webkit node #set should allow me to set the contents of a contenteditable element
     Failure/Error: @session.find(:css,'#blank_content_editable').text.should == 'WYSIWYG'
       expected: "WYSIWYG"
            got: "" (using ==)
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/expectations/fail_with.rb:32:in `fail_with'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:56:in `fail_with_message'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:94:in `__delegate_operator'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:84:in `eval_match'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-expectations-2.14.1/lib/rspec/matchers/operator_matcher.rb:37:in `block in use_custom_matcher_or_delegate'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/capybara-2.2.0/lib/capybara/spec/session/node_spec.rb:116:in `block (3 levels) in <top (required)>'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `instance_eval'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:114:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example.rb:111:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:400:in `block in run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:396:in `run_examples'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:381:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/example_group.rb:382:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `map'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:28:in `block in run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/reporter.rb:58:in `report'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/command_line.rb:25:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:80:in `run'
     # /Users/betelgeuse/.rvm/gems/ruby-2.0.0-p247/gems/rspec-core-2.14.4/lib/rspec/core/runner.rb:17:in `block in autorun'
```
