### ISSUE TITLE
Failed to click because of overlapping element with background image

### ISSUE THREAD

**Issue by brysgo** [thoughtbot/capybara-webkit#642]
We have two section elements overlaying each-other. The one on bottom has a background image and the one on top has a button.

This is the element on bottom's style:
```css
.bottom-element {
  background-attachment: fixed;
  background-image: url(example.jpg);
  background-position: bottom center;
  bottom: 0;
  display: block;
  left: 0;
  padding-top: 8em;
  position: fixed;
  right: 0;
  top: 0;
}
```
This is the top element's style:
```css
.top-element {
  position: fixed;
  top: 0px;
  right: 0px;
  left: 0px;
  background: #20292f;
  box-shadow: 0 0.25em 1em rgba(0, 0, 0, 0.5);
  display: none;
  padding: 2em;
  z-index: 99;
}
```

When we remove the background image from the bottom element or run the test in selenium it passes. But with the background image there in capybara-webkit, it fails to click the button because of the 'overlapping element'. Any thoughts?
