### ISSUE TITLE
CircleCI with Qt5

### ISSUE THREAD

**Issue by reconbot** [thoughtbot/capybara-webkit#786]
Has anyone gotten capybara-webkit to run on circle ci with QT5? We've been having issues with QT 4.8 and upgraded our dev machines only to find out our CI isn't so easy to work with.

Thanks

**Comment by jferris** [comment]
I haven't set this up for a little bit, but there are two parts: you'll need to install the Qt 5 packages, and you'll need to configure the `qmake` path, because Ubuntu installs it somewhere weird.

Here's some minimal configuration to start with:

``` yml
dependencies:
  pre:
    - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo apt-get -y update; true
    - sudo apt-get -y install qtdeclarative5-dev libqt5webkit5-dev
machine:
  environment:
    QMAKE: "/usr/lib/x86_64-linux-gnu/qt5/bin/qmake"
```
