### ISSUE TITLE
JavaScript does not work on Travis?

### ISSUE THREAD

**Issue by chenasraf** [thoughtbot/capybara-webkit#893]
We got it to work once briefly, but it keeps going back to failing. All tests fail because CSS selectors aren't found on the page. When I output the page content on the log, I get only static HTML content **before** the JS loads and modifies the DOM (I'm using Angular.js).

This **only** happens on Travis. Locally running all the tests succeeds without fail.

I'm really not sure what to do. Here are the relevant files:

##### spec_helper.rb
```ruby
RSpec.configure do |config|
  config.include LoginSupport, type: :feature
  config.include Capybara::DSL
  config.include FactoryGirl::Syntax::Methods
  FactoryGirl.definition_file_paths = [File.expand_path('../factories', __FILE__)]

  Capybara.default_driver = :webkit
  Capybara.javascript_driver = :webkit

  Capybara::Webkit.configure do |config|
    config.allow_unknown_urls
  end

  config.verbose_retry = true
  config.default_retry_count = 2
  config.exceptions_to_retry = [Net::ReadTimeout, Capybara::ElementNotFound]

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
end
```

##### rails_helper.rb
```ruby
ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|
  config.use_transactional_fixtures = false
  config.render_views

  DatabaseCleaner[:active_record].strategy = :transaction
  DatabaseCleaner.strategy = :transaction

  config.before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
    DatabaseCleaner.clean

    puts "Seeding data for \##{ENV['test_impersonate_id']}...".red
    SeedSupport.seed_data_for(ENV['test_impersonate_id'])

    DatabaseCleaner.strategy = :transaction
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.append_after(:each) do
    DatabaseCleaner.clean
  end
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
end
```

##### Example spec:

```ruby
RSpec.describe 'ProspectsPage', type: :feature, :js => true do
  before :each do
    LoginSupport.login
    @user_id ||= LoginSupport.current_user.id
  end

  context "active view" do
    context "unfiltered" do
      it "should display all prospects when not filtered" do
        tab_count = find('.tab-prospects .num').text.to_i
        headline_count = find('#table-legend .count .full-count').text.to_i # el not found
        actual_count = Person.my(@user_id).count.to_i

        puts page.body # outputs pre-JS HTML

        expect(tab_count).to eql headline_count
        expect(tab_count).to eql actual_count
      end
    end
  end
end
```

##### .travis.yml

```yaml

language: ruby
rvm:
  - 2.2.4
sudo: false
env:
  global:
    - TRAVIS=true
branches:
  only:
    - master
    - development
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp obfuscated obfuscated
  - mkdir -p tmp
  - sleep 5
cache: bundler
addons:
  postgresql: "9.4"
script:
  - RAILS_ENV=test bundle exec rake db:migrate &>/dev/null
  - bundle exec rake db:test:prepare &>/dev/null
  - bundle exec rake assets:precompile &>/dev/null
  - bundle exec rspec
notifications:
  slack:
    rooms:
      - obfuscated
    on_success: change
    on_failure: always
services:
  - redis-server
```
