### ISSUE TITLE
CI test fails on travis-ci

### ISSUE THREAD

**Issue by rainchen** [thoughtbot/capybara-webkit#933]
Every thing works fine on my local MacOS box(using QT 5.5) but CI test fails on travis-ci.

Here is travis-ci build result: https://travis-ci.org/rainchen/react-rails-img/builds/150243935

it stopped at:

```
$ xvfb-run bundle exec rake
xvfb-run: error: Xvfb failed to start
```

and here is the content of `.travis.yml`:

```
language: ruby
rvm:
  - 2.2.2
env:
  global:
    - JAVASCRIPT_DRIVER=webkit_debug
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script: xvfb-run bundle exec rake
```

Tried several times but all failed:

https://travis-ci.org/rainchen/react-rails-img/builds/150224839
https://travis-ci.org/rainchen/react-rails-img/builds/150222985
https://travis-ci.org/rainchen/react-rails-img/builds/150221369
https://travis-ci.org/rainchen/react-rails-img/builds/150220253

**Comment by mhoran** [comment]
Use either xvfb-run OR an init script, not both.

**Comment by rainchen** [comment]
@mhoran 

already tried, all failed, see those travis-ci results.

only using `xvfb start` in before_script:
https://travis-ci.org/rainchen/react-rails-img/builds/150224839

```
0.00s$ export DISPLAY=:99.0
before_script.2
0.01s$ sh -e /etc/init.d/xvfb start
Starting virtual X frame buffer: Xvfb.
before_script.3
3.01s$ sleep 3
17.20s$ bundle exec rake

```


---

only using `xvfb-run`:
https://travis-ci.org/rainchen/react-rails-img/builds/150220253

```
91.51s$ bundle install --jobs=3 --retry=3
19.10s$ xvfb-run bundle exec rake

WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt. You're using version 4.8.1.

```

---

I think I need a guide for how to config `.travis.yml` to use qt5 in travis-ci.

**Comment by rainchen** [comment]
I finally got test passed on travis-ci, using following `.travis.yml` config:

```
# to get capybara-webkit work with qt5
# refs:
# - http://stackoverflow.com/questions/37201085/unable-to-locate-package-libqt5webkit5-dev
# - https://docs.travis-ci.com/user/trusty-ci-environment#tl%3Bdr---Using-Trusty
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev
script: xvfb-run bundle exec rake
```
